routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/data-tables', function () {
    return view('data');
});

// Resource Route
Route::resource('pertanyaan', 'PertanyaanController');

// Route::get('/pertanyaan', 'PertanyaanController@index');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::get('/pertanyaan/{id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{id}', 'PertanyaanController@update');
// Route::delete('pertanyaan/{id}', 'PertanyaanController@destroy');

// Route::resource('tanya', 'TanyaController');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    // Kalau nama tabelnya tidak sesuai konvensi pakai ini
    // protected $table = 'pertanyaan';

    // Kalau primary keynya bukan 'id' pakai ini
    // protected $primaryKey = 'questions_id'

    public $timestamps = false;

    // whitelist = $fillable
    // blacklist = $guarded
    protected $fillable = ['judul', 'isi', 'tanggal_dibuat'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Question;
use DB;

class PertanyaanController extends Controller
{
    public function index() {
      // Query Builder
      // $posts = DB::table('questions')->get();

      //Eloquent ORM
      $questions = Question::all();

      return view('questions.list', compact('questions'));
    }

    public function create() {
      return view('questions.create');
    }

    public function store(Request $request) {
      // Query Builder
      // $query = DB::table('questions')->insert([
      //                 "judul" => $request["judul-pertanyaan"],
      //                 "isi" => $request["isi-pertanyaan"],
      //                 "tanggal_dibuat" => date('Y-m-d')
      //               ]);

      // Eloquent ORM
      // $question = new Question;
      // $question->judul = $request['judul-pertanyaan'];
      // $question->isi = $request['isi-pertanyaan'];
      // $question->tanggal_dibuat = date('Y-m-d');
      // $question->save();

      // Mass Assignment Eloquent ORM
      Question::create([
        'judul' => $request['judul-pertanyaan'],
        'isi' => $request['isi-pertanyaan'],
        'tanggal_dibuat' => date('Y-m-d')
      ]);

      return redirect('/pertanyaan');
    }

    public function show($id) {
      // Query Builder
      // $post = DB::table('questions')->where('id', $id)->first();

      // Eloquent ORM not primary key
      // $question = Question::where('id', $id)->first();

      // Eloquent ORM using primary key
      $question = Question::find($id);

      return view('questions.show', compact('question'));
    }

    public function edit($id) {
      // Query Builder
      // $post = DB::table('questions')->where('id', $id)->first();

      //Eloquent ORM
      $question = Question::find($id);

      return view('questions.edit', compact('question'));
    }

    public function update($id, Request $request) {
      // Query Builder
      // $query = DB::table('questions')
      //             ->where('id', $id)
      //             ->update([
      //                 'judul'=> $request['judul-pertanyaan'],
      //                 'isi' =>  $request['isi-pertanyaan'],
      //                 'tanggal_diperbaharui' => date('Y-m-d')
      //             ]);

      // Eloquent ORM
      Question::where('id', $id)->update([
        'judul' => $request['judul-pertanyaan'],
        'isi' => $request['isi-pertanyaan'],
        'tanggal_diperbaharui' => date('Y-m-d')
      ]);

      return redirect('/pertanyaan');
    }

    public function destroy($id) {
      // Query Builder
      // $query = DB::table('questions')->where('id', $id)->delete();

      // Eloquent ORM
      Question::destroy($id);

      return redirect('/pertanyaan');
    }
}

resources/views/data.blade.php
@extends('layouts.master')

@section('content')
<div class="card">
   <div class="card-header">
     <h3 class="card-title">DataTable with default features</h3>
   </div>
   <!-- /.card-header -->
   <div class="card-body">
     <table id="example1" class="table table-bordered table-striped">
       <thead>
       <tr>
         <th>Rendering engine</th>
         <th>Browser</th>
         <th>Platform(s)</th>
         <th>Engine version</th>
         <th>CSS grade</th>
       </tr>
       </thead>
       <tbody>
       <tr>
         <td>Trident</td>
         <td>Internet
           Explorer 4.0
         </td>
         <td>Win 95+</td>
         <td> 4</td>
         <td>X</td>
       </tr>
       <tr>
         <td>Trident</td>
         <td>Internet
           Explorer 5.0
         </td>
         <td>Win 95+</td>
         <td>5</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Trident</td>
         <td>Internet
           Explorer 5.5
         </td>
         <td>Win 95+</td>
         <td>5.5</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Trident</td>
         <td>Internet
           Explorer 6
         </td>
         <td>Win 98+</td>
         <td>6</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Trident</td>
         <td>Internet Explorer 7</td>
         <td>Win XP SP2+</td>
         <td>7</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Trident</td>
         <td>AOL browser (AOL desktop)</td>
         <td>Win XP</td>
         <td>6</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Firefox 1.0</td>
         <td>Win 98+ / OSX.2+</td>
         <td>1.7</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Firefox 1.5</td>
         <td>Win 98+ / OSX.2+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Firefox 2.0</td>
         <td>Win 98+ / OSX.2+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Firefox 3.0</td>
         <td>Win 2k+ / OSX.3+</td>
         <td>1.9</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Camino 1.0</td>
         <td>OSX.2+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Camino 1.5</td>
         <td>OSX.3+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Netscape 7.2</td>
         <td>Win 95+ / Mac OS 8.6-9.2</td>
         <td>1.7</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Netscape Browser 8</td>
         <td>Win 98SE+</td>
         <td>1.7</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Netscape Navigator 9</td>
         <td>Win 98+ / OSX.2+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.0</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.1</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.1</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.2</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.2</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.3</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.3</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.4</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.4</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.5</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.5</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.6</td>
         <td>Win 95+ / OSX.1+</td>
         <td>1.6</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.7</td>
         <td>Win 98+ / OSX.1+</td>
         <td>1.7</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Mozilla 1.8</td>
         <td>Win 98+ / OSX.1+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Seamonkey 1.1</td>
         <td>Win 98+ / OSX.2+</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Gecko</td>
         <td>Epiphany 2.20</td>
         <td>Gnome</td>
         <td>1.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>Safari 1.2</td>
         <td>OSX.3</td>
         <td>125.5</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>Safari 1.3</td>
         <td>OSX.3</td>
         <td>312.8</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>Safari 2.0</td>
         <td>OSX.4+</td>
         <td>419.3</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>Safari 3.0</td>
         <td>OSX.4+</td>
         <td>522.1</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>OmniWeb 5.5</td>
         <td>OSX.4+</td>
         <td>420</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>iPod Touch / iPhone</td>
         <td>iPod</td>
         <td>420.1</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Webkit</td>
         <td>S60</td>
         <td>S60</td>
         <td>413</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 7.0</td>
         <td>Win 95+ / OSX.1+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 7.5</td>
         <td>Win 95+ / OSX.2+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 8.0</td>
         <td>Win 95+ / OSX.2+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 8.5</td>
         <td>Win 95+ / OSX.2+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 9.0</td>
         <td>Win 95+ / OSX.3+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 9.2</td>
         <td>Win 88+ / OSX.3+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera 9.5</td>
         <td>Win 88+ / OSX.3+</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Opera for Wii</td>
         <td>Wii</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Nokia N800</td>
         <td>N800</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Presto</td>
         <td>Nintendo DS browser</td>
         <td>Nintendo DS</td>
         <td>8.5</td>
         <td>C/A<sup>1</sup></td>
       </tr>
       <tr>
         <td>KHTML</td>
         <td>Konqureror 3.1</td>
         <td>KDE 3.1</td>
         <td>3.1</td>
         <td>C</td>
       </tr>
       <tr>
         <td>KHTML</td>
         <td>Konqureror 3.3</td>
         <td>KDE 3.3</td>
         <td>3.3</td>
         <td>A</td>
       </tr>
       <tr>
         <td>KHTML</td>
         <td>Konqureror 3.5</td>
         <td>KDE 3.5</td>
         <td>3.5</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Tasman</td>
         <td>Internet Explorer 4.5</td>
         <td>Mac OS 8-9</td>
         <td>-</td>
         <td>X</td>
       </tr>
       <tr>
         <td>Tasman</td>
         <td>Internet Explorer 5.1</td>
         <td>Mac OS 7.6-9</td>
         <td>1</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Tasman</td>
         <td>Internet Explorer 5.2</td>
         <td>Mac OS 8-X</td>
         <td>1</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>NetFront 3.1</td>
         <td>Embedded devices</td>
         <td>-</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>NetFront 3.4</td>
         <td>Embedded devices</td>
         <td>-</td>
         <td>A</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>Dillo 0.8</td>
         <td>Embedded devices</td>
         <td>-</td>
         <td>X</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>Links</td>
         <td>Text only</td>
         <td>-</td>
         <td>X</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>Lynx</td>
         <td>Text only</td>
         <td>-</td>
         <td>X</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>IE Mobile</td>
         <td>Windows Mobile 6</td>
         <td>-</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Misc</td>
         <td>PSP browser</td>
         <td>PSP</td>
         <td>-</td>
         <td>C</td>
       </tr>
       <tr>
         <td>Other browsers</td>
         <td>All others</td>
         <td>-</td>
         <td>-</td>
         <td>U</td>
       </tr>
       </tbody>
       <tfoot>
       <tr>
         <th>Rendering engine</th>
         <th>Browser</th>
         <th>Platform(s)</th>
         <th>Engine version</th>
         <th>CSS grade</th>
       </tr>
       </tfoot>
     </table>
   </div>
   <!-- /.card-body -->
</div>
@endsection

@push('scripts')
<script src="{{ asset('/adminlte/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
@endpush

resources/views/index.blade.php
@extends('layouts.master')

@section('content')
  <table class="table table-bordered">
  <thead>
    <tr>
      <th style="width: 10px">#</th>
      <th>Task</th>
      <th>Progress</th>
      <th style="width: 40px">Label</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.</td>
      <td>Update software</td>
      <td>
        <div class="progress progress-xs">
          <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
        </div>
      </td>
      <td><span class="badge bg-danger">55%</span></td>
    </tr>
    <tr>
      <td>2.</td>
      <td>Clean database</td>
      <td>
        <div class="progress progress-xs">
          <div class="progress-bar bg-warning" style="width: 70%"></div>
        </div>
      </td>
      <td><span class="badge bg-warning">70%</span></td>
    </tr>
    <tr>
      <td>3.</td>
      <td>Cron job running</td>
      <td>
        <div class="progress progress-xs progress-striped active">
          <div class="progress-bar bg-primary" style="width: 30%"></div>
        </div>
      </td>
      <td><span class="badge bg-primary">30%</span></td>
    </tr>
    <tr>
      <td>4.</td>
      <td>Fix and squish bugs</td>
      <td>
        <div class="progress progress-xs progress-striped active">
          <div class="progress-bar bg-success" style="width: 90%"></div>
        </div>
      </td>
      <td><span class="badge bg-success">90%</span></td>
    </tr>
  </tbody>
</table>
@endsection

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('/adminlte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('/adminlte/dist/css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">

<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
@include('layouts.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
@include('layouts.partials.mainSidebar')

  <!-- Content Wrapper. Contains page content -->
@include('layouts.partials.contentLayout')
  <!-- /.content-wrapper -->

  <!-- Footer -->
@include('layouts.partials.footer')

  <!-- Control Sidebar -->
@include('layouts.partials.controlSidebar')
  <!-- /.control-sidebar -->

</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('/adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/adminlte/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('/adminlte/dist/js/demo.js') }}"></script>

@stack('scripts')

</body>
</html>

resources/views/layouts/partials/contentLayout.blade.php
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>@yield('pageTitle')</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">@yield('pageTitle')</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">@yield('contentTitle')</h3>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button>
        </div>
      </div>
      <div class="card-body">
        @yield('content')
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        Footer
      </div>
      <!-- /.card-footer-->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>

resources/views/layouts/partials/controlSidebar.blade.php
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
  <div class="float-right d-none d-sm-block">
    <b>Version</b> 3.0.5
  </div>
  <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
  reserved.
</footer>

resources/views/questions/create.blade.php
@extends('layouts.master')

@section('pageTitle')
  Pertanyaan
@endsection

@section('contentTitle')
  Buat Pertanyaan
@endsection

@section('content')
  <form role="form" action="{{ route('pertanyaan.index') }}" method="post">
    @csrf
    <div class="form-group">
      <label>Judul</label>
      <input name="judul-pertanyaan" type="text" class="form-control" placeholder="Masukkan judul ..." required>

      <label>Isi</label>
      <textarea name="isi-pertanyaan" class="form-control" rows="3" placeholder="Masukkan isi ..." required></textarea>
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a> 
        <button id="btnSearch" type="submit" class="btn btn-primary" Style="width: 100px;">Post</button>
      </div>
    </div>
  </form>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.master')

@section('pageTitle')
  Pertanyaan
@endsection

@section('contentTitle')
  Edit Pertanyaan
@endsection

@section('content')
  <form role="form" action="{{ route('pertanyaan.update', ['pertanyaan' => $question->id]) }}" method="post">
    @csrf

    @method('PUT')

    <div class="form-group">
      <label>Judul</label>
      <input name="judul-pertanyaan" type="text" class="form-control" value="{{ $question->judul }}" placeholder="Masukkan judul ...">

      <label>Isi</label>
      <input name="isi-pertanyaan" class="form-control" rows="3" value="{{ $question->isi }}" placeholder="Masukkan isi ...">
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
        <button id="btnSearch" type="submit" class="btn btn-primary" Style="width: 100px;">Edit</button>
      </div>
    </div>
  </form>
@endsection

resources/views/questions/list.blade.php
@extends('layouts.master')

@section('pageTitle')
  Pertanyaan
@endsection

@section('contentTitle')
  List Pertanyaan
@endsection

@section('content')
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 10px">id</th>
        <th style="width: 200px">Judul</th>
        <th style="width: 350px">Isi</th>
        <th style="width: 100px">Dibuat</th>
        <th style="width: 100px">Diperbaharui</th>
        <th style="width: 60px">Aksi</th>
      </tr>
    </thead>
    <tbody>
      @forelse($questions as $key => $question)
        <tr>
          <td>{{ $question->id }}</td>
          <td>{{ $question->judul }}</td>
          <td>{{ $question->isi }}</td>
          <td>{{ $question->tanggal_dibuat }}</td>
          <td>{{ $question->tanggal_diperbaharui }}</td>
          <td style="display: flex">
            <a href="{{ route('pertanyaan.show', ['pertanyaan' => $question->id]) }}" class="btn btn-info btn-sm">S</a>
            <a href="{{ route('pertanyaan.edit', ['pertanyaan' => $question->id]) }}" class="btn btn-default btn-sm">E</a>
            <form action="{{ route('pertanyaan.destroy', ['pertanyaan' => $question->id]) }}" method="post">
              @csrf
              @method('DELETE')
              <input type="submit" name="delete" value="D" class="btn btn-danger btn-sm">
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="6" align="center">No Data</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="mt-4">
    <form role="form" action="{{ route('pertanyaan.create') }}" method="get">
      <div class="text-right">
        <button type="submit" name="button" class="btn btn-primary ">Buat</button>
      </div>
    </form>
  </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.master')

@section('pageTitle')
  Pertanyaan
@endsection

@section('contentTitle')
  Detail Pertanyaan
@endsection

@section('content')
  <h1>{{ $question->judul }}</h1>
  <p>{{ $question->isi }}</p>

  <div class="row mt-4">
    <div class="col-sm-12 text-right">
      <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
      <a href="{{ route('pertanyaan.edit', ['pertanyaan' => $question->id]) }}" class="btn btn-primary">Edit</a>
    </div>
  </div>
@endsection